ProjektPin/Controllers/IzletiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjektPin.Data;
using ProjektPin.Models;

namespace ProjektPin.Controllers
{
    public class IzletiController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IzletiController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Izleti
        [Authorize]
        public async Task<IActionResult> Index(string search)
        {
          
            if (!String.IsNullOrEmpty(search))
            {
                ViewBag.Search = search;
                var izletiSearch = from ljubimci in _context.Izleti select ljubimci;
                izletiSearch = izletiSearch.Where(Izleti => Izleti.Naziv.Contains(search));
                return View(izletiSearch.ToList());
            }
            return View(await _context.Izleti.ToListAsync());
        }

        // GET: Izleti/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var izleti = await _context.Izleti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (izleti == null)
            {
                return NotFound();
            }

            return View(izleti);
        }

        // GET: Izleti/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Izleti/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Mjesto,Date")] Izleti izleti)
        {
            if (ModelState.IsValid)
            {
                _context.Add(izleti);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(izleti);
        }

        // GET: Izleti/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var izleti = await _context.Izleti.FindAsync(id);
            if (izleti == null)
            {
                return NotFound();
            }
            return View(izleti);
        }

        // POST: Izleti/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Mjesto,Date")] Izleti izleti)
        {
            if (id != izleti.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(izleti);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IzletiExists(izleti.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(izleti);
        }

        // GET: Izleti/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var izleti = await _context.Izleti
                .FirstOrDefaultAsync(m => m.Id == id);
            if (izleti == null)
            {
                return NotFound();
            }

            return View(izleti);
        }

        // POST: Izleti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var izleti = await _context.Izleti.FindAsync(id);
            _context.Izleti.Remove(izleti);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IzletiExists(int id)
        {
            return _context.Izleti.Any(e => e.Id == id);
        }
    }
}

ProjektPin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Izleti</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blue border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Naslovnica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Izleti" asp-action="Index">Izleti</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>